// Package triggermessage implements the OCPP 1.6 TriggerMessage message pair.
//
// # What It Means
//
// TriggerMessage lets the Central System ask the Charge Point to send a
// specific Charge Point-initiated message on demand. The Central System names
// the message type it wants to receive and optionally the connectorId the
// request should target. The Charge Point replies first with
// TriggerMessage.conf — Accepted, Rejected, or NotImplemented — and then,
// if accepted, sends the requested message.
//
// # When It Is Used
//
// The Central System sends TriggerMessage.req to poll current state without
// waiting for the next scheduled message: requesting an immediate Heartbeat for
// clock verification, a StatusNotification to check connector state, a
// BootNotification to re-read hardware identity, or a MeterValues to get the
// latest readings. When connectorId is relevant to the requested message type
// but is absent, the request is interpreted as targeting all connectors.
// TriggerMessage is for current state only; it is not a mechanism for fetching
// historical data.
//
// # What It Is Not
//
// TriggerMessage cannot trigger StartTransaction or StopTransaction because
// those messages represent state transitions, not current state snapshots.
// An Accepted response does not guarantee the message will arrive immediately;
// if the same message is naturally generated by the Charge Point before the
// trigger is fulfilled it may count as satisfying the request. TriggerMessage
// is not a general-purpose RPC or remote procedure mechanism; it only works for
// messages the Charge Point already knows how to generate.
//
// # Adjacent Concepts
//
//   - heartbeat: one of the messages commonly requested via TriggerMessage for
//     on-demand clock synchronization checks.
//   - statusnotification: frequently requested via TriggerMessage to poll the
//     current connector or Charge Point state.
//   - metervalues: can be triggered to retrieve the most recent sampled
//     readings outside the normal periodic schedule.
//   - bootnotification: can be requested during the Pending state to
//     re-register a Charge Point without a physical reboot.
//   - firmwarestatusnotification / diagnosticsstatusnotification: can be
//     triggered to query the current firmware update or diagnostics
//     upload state.
package triggermessage
